HairSalon/Models/Client.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string ClientName { get; set; }
    public string PhoneNumber { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }

}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Client> Clients { get; set; }
    public DbSet<Stylist> Stylists { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public int StylistId { get; set; }
    public string StylistName { get; set; }
    public string StylistPhone { get; set; }
    public string Specialty { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(clients => clients.Stylist).ToList();
      return View(model);
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "StylistName");
      return View();
    }
    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "StylistName");
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      thisStylist.Clients = _db.Clients.Where(clients => clients.StylistId == id).ToList();
      return View(thisStylist);
    }

    public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4 class="text-center">Add a new Client</h4>
<hr>
<div class="col-md-6 offset-md-3">
  @using (Html.BeginForm())
  {
    <div class="form-group">
      Client's Name: @Html.TextBoxFor(model => model.ClientName, new { @class = "form-control", required = "required"})
    </div>
    <div class="form-group">
      Client's Phone Number: @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control", required = "required"})
    </div>
    <div class="form-group">
      Choose a stylist for this client: @Html.DropDownList("StylistId")
    </div>

    <input type="submit" value="Add this Client" class="btn btn-outline-info my-2 my-sm-0">
  }
</div>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Are you sure you want to delete this entry?</h4>

Client Name: @Html.DisplayFor(model => model.ClientName) <br>
Client Phone Number: @Html.DisplayFor(model => model.PhoneNumber)
<hr>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
<hr>
<p>@Html.ActionLink("Back to Clients", "Index") | @Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Client info:</h4>
<hr>

  <p>Client Name: @Html.DisplayFor(model => model.ClientName)</p>
  <p>Client Phone: @Html.DisplayFor(model => model.PhoneNumber)</p>

  <hr>
  <p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId }) | @Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h4>Edit Client Details for: @Html.DisplayFor(model => model.ClientName)</h4>
<hr>
<div class="col-md-6 offset-md-3">
  @using (Html.BeginForm())
  {
    <div class="form-group">
      @Html.HiddenFor(model => model.ClientId)
    </div>
    <div class="form-group">
      Client's Name: 
      @Html.EditorFor(model => model.ClientName, new { @class = "form-control"})
    </div>
    <div class="form-group">
      Client's Phone Number: 
      @Html.EditorFor(model => model.PhoneNumber, new { @class = "form-control"})
    </div>
    <div class="form-group">
      Client's Stylist: 
      @Html.DropDownList("StylistId")
    </div>
      <input type="submit" value="Save" class="btn btn-info">
  }
</div>
<p>@Html.ActionLink("Back to Client List", "Index") | @Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<div class="col-md-8 offset-md-2">
  <h4>Clients</h4>
</div>
<hr>

@if (@Model.Count == 0)
{
  <h4>No clients are in the list.</h4>
} 
<div class="col-md-8 offset-md-2">
  @foreach (Client client in Model)
  {
    <li>@Html.ActionLink($"{client.ClientName}", "Details", new { id = client.ClientId }) : @client.PhoneNumber
    </li>    
    <hr>
  }
</div>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<img id="splash" src='~/img/salon-splash.jpg'/>
<br>
<h4>@Html.ActionLink("List of Stylists", "Index", "Stylists")</h4>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
    <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative&display=swap" rel="stylesheet">
    <title>Eau Claire's Hair Salon</title>
  </head>
  <body>
    <div class="container">
      <h1>Eau Claire's Hair Salon</h1>
      <hr>
        @RenderBody()
    </div>
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4 class="text-center">Add a Stylist</h4>
<hr>
<div class="col-md-6 offset-md-3">
  @using (Html.BeginForm())
  {
    <div class="form-group">
      <p>Stylist's Name:
      @Html.TextBoxFor(model => model.StylistName, new { @class = "form-control", required = "required"})</p>
    </div>
    <div class="form-group">
      <p>Stylist's Phone Number:
      @Html.TextBoxFor(model => model.StylistPhone, new { @class = "form-control", required = "required"})</p>
    </div>
    <div class="form-group">
      <p>Stylist's Speciality:
      @Html.TextBoxFor(model => model.Specialty, new { @class = "form-control"})</p>
    </div>
    <input type="submit" value="Add this Stylist" class="btn btn-outline-info my-2 my-sm-0">
  }
</div>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<p>Are you sure you want to delete stylist @Html.DisplayFor(model => model.StylistName) from the index?</p>

@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
<hr>
<p>@Html.ActionLink("Back to Stylists", "Index") | @Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model HairSalon.Models.Stylist;  

<h4>Stylist Details</h4>
<hr>
<p>Name: @Html.DisplayFor(model => model.StylistName)
<br>
Phone: @Html.DisplayFor(model => model.StylistPhone)
<br>
Personal Specialty: @Html.DisplayFor(model => model.Specialty)</p>
<hr>

@if (@Model.Clients.Count == 0) 
{
  <p>No clients have been added.</p>
}
@foreach (Client client in Model.Clients)
{
  <p>Name: @client.ClientName</p>
}

<p>@Html.ActionLink("Add a client", "Create", "Clients")</p>
<hr>
<p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId }) | @Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId }) | @Html.ActionLink("Back to Stylists", "Index") | @Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4>Edit Stylist Entry for: @Html.DisplayFor(model => model.StylistName)</h4>
<hr>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)
  <p>Stylist's Name: @Html.EditorFor(model => model.StylistName)</p>
  <p>Stylist's Phone Number: @Html.EditorFor(model => model.StylistPhone)</p>
  <p>Stylist's Specialty: @Html.EditorFor(model => model.Specialty)</p>
  <hr>
  <input type="submit" value="Save" class="btn btn-outline-info my-2 my-sm-0"/>
}
<br>
<p>@Html.ActionLink("Back to stylists", "Index") | @Html.ActionLink("Home", "Index", "Home")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
} 

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

<h4>Current Index of Stylists:</h4>
<hr>

@if (@Model.Count == 0)
{
  <p>No stylists have been added yet! @Html.ActionLink("Click Here", "Create", "Stylists") to add one.</p>
  <hr>
} 
@foreach (Stylist stylist in Model)
{
  <li>@Html.ActionLink($"{stylist.StylistName}", "Details", new { id = stylist.StylistId }): @stylist.StylistPhone</li>
  <hr>
}

<p>@Html.ActionLink("Add a new Stylist", "Create", "Stylists") | @Html.ActionLink("Home", "Index", "Home")</p>